# Generated by Django 4.2.16 on 2024-12-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_total_data_order_vendors_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax_data',
            field=models.JSONField(blank=True, help_text='Data format: {"tax_type":{"tax_percentage":"tax_amount"}}', null=True),
        ),
    ]
